-- 火山引擎建表和查询SQL语句
-- 生成时间: 2025-10-15 19:17:22
-- Catalog: hive_catalog
-- Database: test_db

-- 表: CaseHistory OK
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`CaseHistory`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`CaseHistory` (
  `Id` STRING,
  `IsDeleted` BOOLEAN,
  `CaseId` STRING,
  `CreatedById` STRING,
  `CreatedDate` TIMESTAMP,
  `Field` STRING,
  `DataType` STRING,
  `OldValue` STRING,
  `NewValue` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/CaseHistory';



-- 表: Event OK
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Event`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Event` (
  `Id` STRING,
  `WhoId` STRING,
  `WhatId` STRING,
  `Subject` STRING,
  `Location` STRING,
  `IsAllDayEvent` BOOLEAN,
  `ActivityDateTime` TIMESTAMP,
  `ActivityDate` DATE,
  `DurationInMinutes` BIGINT,
  `StartDateTime` TIMESTAMP,
  `EndDateTime` TIMESTAMP,
  `EndDate` DATE,
  `Description` STRING,
  `AccountId` STRING,
  `OwnerId` STRING,
  `IsPrivate` BOOLEAN,
  `ShowAs` STRING,
  `IsChild` BOOLEAN,
  `IsGroupEvent` BOOLEAN,
  `GroupEventType` STRING,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `RecurrenceActivityId` STRING,
  `IsRecurrence` BOOLEAN,
  `RecurrenceStartDateTime` TIMESTAMP,
  `RecurrenceEndDateOnly` DATE,
  `RecurrenceTimeZoneSidKey` STRING,
  `RecurrenceType` STRING,
  `RecurrenceInterval` BIGINT,
  `RecurrenceDayOfWeekMask` BIGINT,
  `RecurrenceDayOfMonth` BIGINT,
  `RecurrenceInstance` STRING,
  `RecurrenceMonthOfYear` STRING,
  `ReminderDateTime` TIMESTAMP,
  `IsReminderSet` BOOLEAN,
  `EventSubtype` STRING,
  `IsRecurrence2Exclusion` BOOLEAN,
  `Recurrence2PatternText` STRING,
  `Recurrence2PatternVersion` STRING,
  `IsRecurrence2` BOOLEAN,
  `IsRecurrence2Exception` BOOLEAN,
  `Recurrence2PatternStartDate` TIMESTAMP,
  `Recurrence2PatternTimeZone` STRING,
  `Recordstamp` TIMESTAMP,
  `CurrencyIsoCode` STRING,
  `Who_Type` STRING,
  `What_Type` STRING,
  `Owner_Type` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Event';



-- 表: Lead OK
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Lead`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Lead` (
  `Id` STRING,
  `MasterRecordId` STRING,
  `LastName` STRING,
  `FirstName` STRING,
  `Salutation` STRING,
  `Name` STRING,
  `RecordTypeId` STRING,
  `Title` STRING,
  `Company` STRING,
  `Street` STRING,
  `City` STRING,
  `State` STRING,
  `PostalCode` STRING,
  `Country` STRING,
  `Latitude` DOUBLE,
  `Longitude` DOUBLE,
  `GeocodeAccuracy` STRING,
  `Phone` STRING,
  `Email` STRING,
  `Website` STRING,
  `PhotoUrl` STRING,
  `Description` STRING,
  `LeadSource` STRING,
  `Status` STRING,
  `Industry` STRING,
  `Rating` STRING,
  `AnnualRevenue` DOUBLE,
  `NumberOfEmployees` BIGINT,
  `OwnerId` STRING,
  `IsConverted` BOOLEAN,
  `ConvertedDate` DATE,
  `ConvertedAccountId` STRING,
  `ConvertedContactId` STRING,
  `ConvertedOpportunityId` STRING,
  `IsUnreadByOwner` BOOLEAN,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `LastActivityDate` DATE,
  `LastViewedDate` TIMESTAMP,
  `LastReferencedDate` TIMESTAMP,
  `Jigsaw` STRING,
  `JigsawContactId` STRING,
  `EmailBouncedReason` STRING,
  `EmailBouncedDate` TIMESTAMP,
  `IndividualId` STRING,
  `Recordstamp` TIMESTAMP,
  `CurrencyIsoCode` STRING,
  `IsPriorityRecord` BOOLEAN,
  `Owner_Type` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Lead';


-- 表: CurrencyType OK
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`CurrencyType`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`CurrencyType` (
  `Id` STRING,
  `IsoCode` STRING,
  `ConversionRate` DOUBLE,
  `DecimalPlaces` BIGINT,
  `IsActive` BOOLEAN,
  `IsCorporate` BOOLEAN,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `Recordstamp` TIMESTAMP
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/CurrencyType';



-- 表: OpportunityHistory OK
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`OpportunityHistory`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`OpportunityHistory` (
  `Id` STRING,
  `OpportunityId` STRING,
  `CreatedById` STRING,
  `CreatedDate` TIMESTAMP,
  `StageName` STRING,
  `Amount` DOUBLE,
  `ExpectedRevenue` DOUBLE,
  `CloseDate` DATE,
  `Probability` DOUBLE,
  `ForecastCategory` STRING,
  `CurrencyIsoCode` STRING,
  `SystemModstamp` TIMESTAMP,
  `IsDeleted` BOOLEAN,
  `PrevAmount` DOUBLE,
  `PrevCloseDate` DATE
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/OpportunityHistory';

-- 表: User
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`User`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`User` (
  `Id` STRING,
  `Username` STRING,
  `LastName` STRING,
  `FirstName` STRING,
  `Name` STRING,
  `CompanyName` STRING,
  `Division` STRING,
  `Department` STRING,
  `Title` STRING,
  `Street` STRING,
  `City` STRING,
  `State` STRING,
  `PostalCode` STRING,
  `Country` STRING,
  `Latitude` DOUBLE,
  `Longitude` DOUBLE,
  `GeocodeAccuracy` STRING,
  `Email` STRING,
  `EmailPreferencesAutoBcc` BOOLEAN,
  `SenderEmail` STRING,
  `SenderName` STRING,
  `Signature` STRING,
  `Phone` STRING,
  `Fax` STRING,
  `MobilePhone` STRING,
  `Alias` STRING,
  `CommunityNickname` STRING,
  `BadgeText` STRING,
  `IsActive` BOOLEAN,
  `TimeZoneSidKey` STRING,
  `UserRoleId` STRING,
  `LocaleSidKey` STRING,
  `EmailEncodingKey` STRING,
  `ProfileId` STRING,
  `UserType` STRING,
  `LanguageLocaleKey` STRING,
  `EmployeeNumber` STRING,
  `DelegatedApproverId` STRING,
  `ManagerId` STRING,
  `LastLoginDate` TIMESTAMP,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `ForecastEnabled` BOOLEAN,
  `ContactId` STRING,
  `AccountId` STRING,
  `CallCenterId` STRING,
  `Extension` STRING,
  `FederationIdentifier` STRING,
  `AboutMe` STRING,
  `FullPhotoUrl` STRING,
  `SmallPhotoUrl` STRING,
  `MediumPhotoUrl` STRING,
  `DigestFrequency` STRING,
  `DefaultGroupNotificationFrequency` STRING,
  `LastViewedDate` TIMESTAMP,
  `LastReferencedDate` TIMESTAMP,
  `BannerPhotoUrl` STRING,
  `SmallBannerPhotoUrl` STRING,
  `MediumBannerPhotoUrl` STRING,
  `IsProfilePhotoActive` BOOLEAN,
  `IndividualId` STRING,
  `Recordstamp` TIMESTAMP,
  `EmailPreferencesAutoBccStayInTouch` BOOLEAN,
  `EmailPreferencesStayInTouchReminder` BOOLEAN,
  `StayInTouchSubject` STRING,
  `StayInTouchSignature` STRING,
  `StayInTouchNote` STRING,
  `ReceivesInfoEmails` BOOLEAN,
  `ReceivesAdminInfoEmails` BOOLEAN,
  `DefaultCurrencyIsoCode` STRING,
  `CurrencyIsoCode` STRING,
  `OfflineTrialExpirationDate` TIMESTAMP,
  `OfflinePdaTrialExpirationDate` TIMESTAMP,
  `UserPermissionsMarketingUser` BOOLEAN,
  `UserPermissionsOfflineUser` BOOLEAN,
  `UserPermissionsAvantgoUser` BOOLEAN,
  `UserPermissionsCallCenterAutoLogin` BOOLEAN,
  `UserPermissionsSFContentUser` BOOLEAN,
  `UserPermissionsKnowledgeUser` BOOLEAN,
  `UserPermissionsInteractionUser` BOOLEAN,
  `UserPermissionsSupportUser` BOOLEAN,
  `UserPreferencesActivityRemindersPopup` BOOLEAN,
  `UserPreferencesEventRemindersCheckboxDefault` BOOLEAN,
  `UserPreferencesTaskRemindersCheckboxDefault` BOOLEAN,
  `UserPreferencesReminderSoundOff` BOOLEAN,
  `UserPreferencesDisableAllFeedsEmail` BOOLEAN,
  `UserPreferencesDisableFollowersEmail` BOOLEAN,
  `UserPreferencesDisableProfilePostEmail` BOOLEAN,
  `UserPreferencesDisableChangeCommentEmail` BOOLEAN,
  `UserPreferencesDisableLaterCommentEmail` BOOLEAN,
  `UserPreferencesDisProfPostCommentEmail` BOOLEAN,
  `UserPreferencesApexPagesDeveloperMode` BOOLEAN,
  `UserPreferencesReceiveNoNotificationsAsApprover` BOOLEAN,
  `UserPreferencesReceiveNotificationsAsDelegatedApprover` BOOLEAN,
  `UserPreferencesHideCSNGetChatterMobileTask` BOOLEAN,
  `UserPreferencesDisableMentionsPostEmail` BOOLEAN,
  `UserPreferencesDisMentionsCommentEmail` BOOLEAN,
  `UserPreferencesHideCSNDesktopTask` BOOLEAN,
  `UserPreferencesHideChatterOnboardingSplash` BOOLEAN,
  `UserPreferencesHideSecondChatterOnboardingSplash` BOOLEAN,
  `UserPreferencesDisCommentAfterLikeEmail` BOOLEAN,
  `UserPreferencesDisableLikeEmail` BOOLEAN,
  `UserPreferencesSortFeedByComment` BOOLEAN,
  `UserPreferencesDisableMessageEmail` BOOLEAN,
  `UserPreferencesDisableBookmarkEmail` BOOLEAN,
  `UserPreferencesDisableSharePostEmail` BOOLEAN,
  `UserPreferencesEnableAutoSubForFeeds` BOOLEAN,
  `UserPreferencesDisableFileShareNotificationsForApi` BOOLEAN,
  `UserPreferencesShowTitleToExternalUsers` BOOLEAN,
  `UserPreferencesShowManagerToExternalUsers` BOOLEAN,
  `UserPreferencesShowEmailToExternalUsers` BOOLEAN,
  `UserPreferencesShowWorkPhoneToExternalUsers` BOOLEAN,
  `UserPreferencesShowMobilePhoneToExternalUsers` BOOLEAN,
  `UserPreferencesShowFaxToExternalUsers` BOOLEAN,
  `UserPreferencesShowStreetAddressToExternalUsers` BOOLEAN,
  `UserPreferencesShowCityToExternalUsers` BOOLEAN,
  `UserPreferencesShowStateToExternalUsers` BOOLEAN,
  `UserPreferencesShowPostalCodeToExternalUsers` BOOLEAN,
  `UserPreferencesShowCountryToExternalUsers` BOOLEAN,
  `UserPreferencesShowProfilePicToGuestUsers` BOOLEAN,
  `UserPreferencesShowTitleToGuestUsers` BOOLEAN,
  `UserPreferencesShowCityToGuestUsers` BOOLEAN,
  `UserPreferencesShowStateToGuestUsers` BOOLEAN,
  `UserPreferencesShowPostalCodeToGuestUsers` BOOLEAN,
  `UserPreferencesShowCountryToGuestUsers` BOOLEAN,
  `UserPreferencesShowForecastingChangeSignals` BOOLEAN,
  `UserPreferencesLiveAgentMiawSetupDeflection` BOOLEAN,
  `UserPreferencesHideS1BrowserUI` BOOLEAN,
  `UserPreferencesDisableEndorsementEmail` BOOLEAN,
  `UserPreferencesPathAssistantCollapsed` BOOLEAN,
  `UserPreferencesCacheDiagnostics` BOOLEAN,
  `UserPreferencesShowEmailToGuestUsers` BOOLEAN,
  `UserPreferencesShowManagerToGuestUsers` BOOLEAN,
  `UserPreferencesShowWorkPhoneToGuestUsers` BOOLEAN,
  `UserPreferencesShowMobilePhoneToGuestUsers` BOOLEAN,
  `UserPreferencesShowFaxToGuestUsers` BOOLEAN,
  `UserPreferencesShowStreetAddressToGuestUsers` BOOLEAN,
  `UserPreferencesLightningExperiencePreferred` BOOLEAN,
  `UserPreferencesPreviewLightning` BOOLEAN,
  `UserPreferencesHideEndUserOnboardingAssistantModal` BOOLEAN,
  `UserPreferencesHideLightningMigrationModal` BOOLEAN,
  `UserPreferencesHideSfxWelcomeMat` BOOLEAN,
  `UserPreferencesHideBiggerPhotoCallout` BOOLEAN,
  `UserPreferencesGlobalNavBarWTShown` BOOLEAN,
  `UserPreferencesGlobalNavGridMenuWTShown` BOOLEAN,
  `UserPreferencesCreateLEXAppsWTShown` BOOLEAN,
  `UserPreferencesFavoritesWTShown` BOOLEAN,
  `UserPreferencesRecordHomeSectionCollapseWTShown` BOOLEAN,
  `UserPreferencesRecordHomeReservedWTShown` BOOLEAN,
  `UserPreferencesFavoritesShowTopFavorites` BOOLEAN,
  `UserPreferencesExcludeMailAppAttachments` BOOLEAN,
  `UserPreferencesSuppressTaskSFXReminders` BOOLEAN,
  `UserPreferencesSuppressEventSFXReminders` BOOLEAN,
  `UserPreferencesPreviewCustomTheme` BOOLEAN,
  `UserPreferencesHasCelebrationBadge` BOOLEAN,
  `UserPreferencesUserDebugModePref` BOOLEAN,
  `UserPreferencesSRHOverrideActivities` BOOLEAN,
  `UserPreferencesNewLightningReportRunPageEnabled` BOOLEAN,
  `UserPreferencesReverseOpenActivitiesView` BOOLEAN,
  `UserPreferencesHasSentWarningEmail` BOOLEAN,
  `UserPreferencesHasSentWarningEmail238` BOOLEAN,
  `UserPreferencesHasSentWarningEmail240` BOOLEAN,
  `UserPreferencesHideBrowseProductRedirectConfirmation` BOOLEAN,
  `UserPreferencesHideOnlineSalesAppWelcomeMat` BOOLEAN,
  `UserPreferencesShowForecastingRoundedAmounts` BOOLEAN,
  `IsExtIndicatorVisible` BOOLEAN,
  `OutOfOfficeMessage` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/User';

-- 表: Account
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Account`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Account` (
  `Id` STRING,
  `MasterRecordId` STRING,
  `Name` STRING,
  `Type` STRING,
  `RecordTypeId` STRING,
  `ParentId` STRING,
  `BillingStreet` STRING,
  `BillingCity` STRING,
  `BillingState` STRING,
  `BillingPostalCode` STRING,
  `BillingCountry` STRING,
  `BillingLatitude` DOUBLE,
  `BillingLongitude` DOUBLE,
  `ShippingStreet` STRING,
  `ShippingCity` STRING,
  `ShippingState` STRING,
  `ShippingPostalCode` STRING,
  `ShippingCountry` STRING,
  `ShippingLatitude` DOUBLE,
  `ShippingLongitude` DOUBLE,
  `ShippingGeocodeAccuracy` STRING,
  `Phone` STRING,
  `Fax` STRING,
  `Website` STRING,
  `Industry` STRING,
  `AnnualRevenue` DOUBLE,
  `NumberOfEmployees` BIGINT,
  `Description` STRING,
  `OwnerId` STRING,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `LastActivityDate` DATE,
  `LastViewedDate` TIMESTAMP,
  `LastReferencedDate` TIMESTAMP,
  `AccountSource` STRING,
  `SystemModstamp` TIMESTAMP,
  `Recordstamp` TIMESTAMP,
  `BillingGeocodeAccuracy` STRING,
  `AccountNumber` STRING,
  `PhotoUrl` STRING,
  `Rating` STRING,
  `Site` STRING,
  `CurrencyIsoCode` STRING,
  `Jigsaw` STRING,
  `JigsawCompanyId` STRING,
  `SicDesc` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Account';


-- 表: Contact
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Contact`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Contact` (
  `Id` STRING,
  `MasterRecordId` STRING,
  `AccountId` STRING,
  `LastName` STRING,
  `FirstName` STRING,
  `Salutation` STRING,
  `Name` STRING,
  `RecordTypeId` STRING,
  `OtherStreet` STRING,
  `OtherCity` STRING,
  `OtherState` STRING,
  `OtherPostalCode` STRING,
  `OtherCountry` STRING,
  `OtherLatitude` DOUBLE,
  `OtherLongitude` DOUBLE,
  `OtherGeocodeAccuracy` STRING,
  `MailingStreet` STRING,
  `MailingCity` STRING,
  `MailingState` STRING,
  `MailingPostalCode` STRING,
  `MailingCountry` STRING,
  `MailingLatitude` DOUBLE,
  `MailingLongitude` DOUBLE,
  `MailingGeocodeAccuracy` STRING,
  `Phone` STRING,
  `Fax` STRING,
  `MobilePhone` STRING,
  `HomePhone` STRING,
  `OtherPhone` STRING,
  `AssistantPhone` STRING,
  `ReportsToId` STRING,
  `Email` STRING,
  `Title` STRING,
  `Department` STRING,
  `AssistantName` STRING,
  `LeadSource` STRING,
  `Birthdate` DATE,
  `Description` STRING,
  `OwnerId` STRING,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `LastActivityDate` DATE,
  `LastCURequestDate` TIMESTAMP,
  `LastCUUpdateDate` TIMESTAMP,
  `LastViewedDate` TIMESTAMP,
  `LastReferencedDate` TIMESTAMP,
  `EmailBouncedReason` STRING,
  `EmailBouncedDate` TIMESTAMP,
  `IsEmailBounced` BOOLEAN,
  `PhotoUrl` STRING,
  `Jigsaw` STRING,
  `JigsawContactId` STRING,
  `IndividualId` STRING,
  `Recordstamp` TIMESTAMP,
  `CurrencyIsoCode` STRING,
  `IsPriorityRecord` BOOLEAN
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Contact';

-- 表: Opportunity
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Opportunity`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Opportunity` (
  `Id` STRING,
  `AccountId` STRING,
  `RecordTypeId` STRING,
  `Name` STRING,
  `Description` STRING,
  `StageName` STRING,
  `Amount` DOUBLE,
  `Probability` DOUBLE,
  `CloseDate` DATE,
  `Type` STRING,
  `NextStep` STRING,
  `LeadSource` STRING,
  `IsClosed` BOOLEAN,
  `IsWon` BOOLEAN,
  `ForecastCategory` STRING,
  `ForecastCategoryName` STRING,
  `CampaignId` STRING,
  `HasOpportunityLineItem` BOOLEAN,
  `Pricebook2Id` STRING,
  `OwnerId` STRING,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `LastActivityDate` DATE,
  `LastStageChangeDate` TIMESTAMP,
  `FiscalQuarter` BIGINT,
  `FiscalYear` BIGINT,
  `Fiscal` STRING,
  `ContactId` STRING,
  `LastViewedDate` TIMESTAMP,
  `LastReferencedDate` TIMESTAMP,
  `HasOpenActivity` BOOLEAN,
  `HasOverdueTask` BOOLEAN,
  `LastAmountChangedHistoryId` STRING,
  `LastCloseDateChangedHistoryId` STRING,
  `Recordstamp` TIMESTAMP,
  `CurrencyIsoCode` STRING,
  `PushCount` BIGINT
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Opportunity';

-- 表: Case 查询的时候需要加双引号
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Case`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Case` (
  `Id` STRING,
  `MasterRecordId` STRING,
  `CaseNumber` STRING,
  `ContactId` STRING,
  `AccountId` STRING,
  `EntitlementId` STRING,
  `ParentId` STRING,
  `SuppliedName` STRING,
  `SuppliedEmail` STRING,
  `SuppliedPhone` STRING,
  `SuppliedCompany` STRING,
  `Type` STRING,
  `RecordTypeId` STRING,
  `Status` STRING,
  `Reason` STRING,
  `Origin` STRING,
  `Language` STRING,
  `Subject` STRING,
  `Priority` STRING,
  `Description` STRING,
  `IsClosed` BOOLEAN,
  `ClosedDate` TIMESTAMP,
  `IsEscalated` BOOLEAN,
  `OwnerId` STRING,
  `SlaStartDate` TIMESTAMP,
  `SlaExitDate` TIMESTAMP,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `ContactPhone` STRING,
  `ContactMobile` STRING,
  `ContactEmail` STRING,
  `ContactFax` STRING,
  `Comments` STRING,
  `LastViewedDate` TIMESTAMP,
  `LastReferencedDate` TIMESTAMP,
  `Recordstamp` TIMESTAMP,
  `CurrencyIsoCode` STRING,
  `Owner_Type` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Case';


-- 表: Task
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`Task`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`Task` (
  `Id` STRING,
  `WhoId` STRING,
  `WhatId` STRING,
  `Subject` STRING,
  `ActivityDate` DATE,
  `Status` STRING,
  `Priority` STRING,
  `IsHighPriority` BOOLEAN,
  `OwnerId` STRING,
  `Description` STRING,
  `AccountId` STRING,
  `IsClosed` BOOLEAN,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `CallDurationInSeconds` BIGINT,
  `CallType` STRING,
  `CallDisposition` STRING,
  `CallObject` STRING,
  `ReminderDateTime` TIMESTAMP,
  `IsReminderSet` BOOLEAN,
  `RecurrenceActivityId` STRING,
  `IsRecurrence` BOOLEAN,
  `RecurrenceStartDateOnly` DATE,
  `RecurrenceEndDateOnly` DATE,
  `RecurrenceTimeZoneSidKey` STRING,
  `RecurrenceType` STRING,
  `RecurrenceInterval` BIGINT,
  `RecurrenceDayOfWeekMask` BIGINT,
  `RecurrenceDayOfMonth` BIGINT,
  `RecurrenceInstance` STRING,
  `RecurrenceMonthOfYear` STRING,
  `RecurrenceRegeneratedType` STRING,
  `TaskSubtype` STRING,
  `CompletedDateTime` TIMESTAMP,
  `Recordstamp` TIMESTAMP,
  `CurrencyIsoCode` STRING,
  `Who_Type` STRING,
  `What_Type` STRING,
  `Owner_Type` STRING
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/Task';

-- 表: RecordType
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`RecordType`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`RecordType` (
  `Id` STRING,
  `Name` STRING,
  `DeveloperName` STRING,
  `NamespacePrefix` STRING,
  `Description` STRING,
  `BusinessProcessId` STRING,
  `SobjectType` STRING,
  `IsActive` BOOLEAN,
  `CreatedById` STRING,
  `CreatedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `SystemModstamp` TIMESTAMP,
  `Recordstamp` TIMESTAMP
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/RecordType';

-- 表: DatedConversionRate
DROP TABLE IF EXISTS `hive_catalog`.`test_db`.`DatedConversionRate`;

CREATE EXTERNAL TABLE `hive_catalog`.`test_db`.`DatedConversionRate` (
  `Id` STRING,
  `IsoCode` STRING,
  `StartDate` DATE,
  `NextStartDate` DATE,
  `ConversionRate` DOUBLE,
  `CreatedDate` TIMESTAMP,
  `CreatedById` STRING,
  `LastModifiedDate` TIMESTAMP,
  `LastModifiedById` STRING,
  `SystemModstamp` TIMESTAMP,
  `Recordstamp` TIMESTAMP
) 
STORED AS PARQUET 
LOCATION 'tos://wangmeng-test/sample-data/DatedConversionRate';